title: Zee's Blog
email: zyadalyashae@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of the site, e.g. /blog
url: "https://www.alyashaz.com" # the base hostname & protocol for the site, e.g. http://example.com

# Author settings
author: Zyad Alyashae # add your name
author-pic: headshot2.jpg
about-author: "Hey there! I am Zyad Alyashae, but you may refer to me as Zee. I’m a Back-End Software Engineer, occasional photographer, and an avid Soccer fan (Football for those who are outside of North America). Related to dev, I especially enjoy coding in C# and learning new design patterns."

# Contact links
#email: # Email address
#phone: # Phone number
website: alyashaz.github.io # Do not add http://
linkedin: zyad-alyashae-b243b690 # Linkedin handle
github: alyashaz # Github handle
#twitter: # Twitter handle
#facebook: # Facebook handle
instagram:  breathtaking.voyage # Instagram handle
#pinterest: # Pinterest handle

# Newsletter
#mailchimp: # MailChimp form identifier.

# Disqus
#discus_identifier: # discus identifier

# Google Analytics Tracker
analytics: UA-165344084-1

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
